"""initial medication care schema

Revision ID: e6f162c4c514
Revises: 
Create Date: 2026-09-20 13:54:31.629029
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e6f162c4c514'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('care_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_link_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index(op.f('ix_telegram_link_codes_user_id'), 'telegram_link_codes', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['care_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_group_id'), 'audit_logs', ['group_id'], unique=False)
    op.create_table('care_group_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'CAREGIVER', name='grouprole', native_enum=False, length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['care_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member')
    )
    op.create_index(op.f('ix_care_group_members_group_id'), 'care_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_care_group_members_user_id'), 'care_group_members', ['user_id'], unique=False)
    op.create_table('elder_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNDISCLOSED', name='sex', native_enum=False, length=20), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('diagnoses', sa.JSON(), nullable=False),
    sa.Column('current_medications_note', sa.Text(), nullable=True),
    sa.Column('mobility_level', sa.Enum('INDEPENDENT', 'NEEDS_ASSISTANCE', 'WHEELCHAIR', 'BEDRIDDEN', name='mobilitylevel', native_enum=False, length=30), nullable=True),
    sa.Column('sleep_habits', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('height_cm IS NULL OR height_cm > 0', name='ck_elder_height_positive'),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg > 0', name='ck_elder_weight_positive'),
    sa.ForeignKeyConstraint(['group_id'], ['care_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elder_profiles_group_id'), 'elder_profiles', ['group_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'CAREGIVER', name='grouprole', native_enum=False, length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['care_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_invitation_group_email', 'invitations', ['group_id', 'email'], unique=False)
    op.create_table('caregiver_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('elder_id', sa.Uuid(), nullable=False),
    sa.Column('caregiver_user_id', sa.Uuid(), nullable=False),
    sa.Column('can_view_medications', sa.Boolean(), nullable=False),
    sa.Column('can_confirm_doses', sa.Boolean(), nullable=False),
    sa.Column('can_view_diagnoses', sa.Boolean(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['elder_id'], ['elder_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('elder_id', 'caregiver_user_id', name='uq_elder_caregiver')
    )
    op.create_index(op.f('ix_caregiver_assignments_caregiver_user_id'), 'caregiver_assignments', ['caregiver_user_id'], unique=False)
    op.create_index(op.f('ix_caregiver_assignments_elder_id'), 'caregiver_assignments', ['elder_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('elder_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dose_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('dose_unit', sa.String(length=50), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('dose_amount > 0', name='ck_medication_dose_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['elder_id'], ['elder_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_elder_id'), 'medications', ['elder_id'], unique=False)
    op.create_table('medication_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('reminder_offsets_minutes', sa.JSON(), nullable=False),
    sa.Column('escalation_after_minutes', sa.Integer(), nullable=False),
    sa.Column('assigned_caregiver_user_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('escalation_after_minutes > 0', name='ck_schedule_escalation_positive'),
    sa.ForeignKeyConstraint(['assigned_caregiver_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_schedules_medication_id'), 'medication_schedules', ['medication_id'], unique=False)
    op.create_table('dose_occurrences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'DUE', 'ADMINISTERED', 'CANNOT_ADMINISTER', 'UNCONFIRMED', 'CANCELLED', name='dosestatus', native_enum=False, length=30), nullable=False),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'scheduled_for', name='uq_schedule_occurrence_time')
    )
    op.create_index('ix_dose_due', 'dose_occurrences', ['status', 'next_action_at'], unique=False)
    op.create_table('dose_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('responded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('response_type', sa.Enum('ADMINISTERED', 'CANNOT_ADMINISTER', name='doseresponsetype', native_enum=False, length=30), nullable=False),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['dose_occurrences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('occurrence_id')
    )
    op.create_table('notification_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('REMINDER', 'ESCALATION', name='notificationkind', native_enum=False, length=20), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('delivery_attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['dose_occurrences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('occurrence_id', 'recipient_user_id', 'kind', 'ordinal', name='uq_notification_attempt')
    )
    op.create_index(op.f('ix_notification_attempts_occurrence_id'), 'notification_attempts', ['occurrence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_attempts_occurrence_id'), table_name='notification_attempts')
    op.drop_table('notification_attempts')
    op.drop_table('dose_responses')
    op.drop_index('ix_dose_due', table_name='dose_occurrences')
    op.drop_table('dose_occurrences')
    op.drop_index(op.f('ix_medication_schedules_medication_id'), table_name='medication_schedules')
    op.drop_table('medication_schedules')
    op.drop_index(op.f('ix_medications_elder_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_caregiver_assignments_elder_id'), table_name='caregiver_assignments')
    op.drop_index(op.f('ix_caregiver_assignments_caregiver_user_id'), table_name='caregiver_assignments')
    op.drop_table('caregiver_assignments')
    op.drop_index('ix_invitation_group_email', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_elder_profiles_group_id'), table_name='elder_profiles')
    op.drop_table('elder_profiles')
    op.drop_index(op.f('ix_care_group_members_user_id'), table_name='care_group_members')
    op.drop_index(op.f('ix_care_group_members_group_id'), table_name='care_group_members')
    op.drop_table('care_group_members')
    op.drop_index(op.f('ix_audit_logs_group_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_telegram_link_codes_user_id'), table_name='telegram_link_codes')
    op.drop_table('telegram_link_codes')
    op.drop_table('care_groups')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

